---
train:
  params:
    batch_size: 64
    epoch: 20
    lr: 0.00001
    decay: 0.1
    decay_step: 5000
    loss: L1Loss
  save:
    save_path: "/home/cyh/GazeBenchmark/exp/Implementation/Full-Face-eth-20epoch"
    model_name: weight
    step: 5
  data:
    image: "/home/cyh/GazeDataset20200519/FaceBased/ETH-Gaze/Image/train"
    label: "/home/cyh/GazeDataset20200519/FaceBased/ETH-Gaze/Label/train.label"
  pretrains: "None"

valid:
   load:
      begin_step: 5
      end_step: 5
      steps: 5
      load_path: "/home/cyh/GazeBenchmark/exp/Implementation/Full-Face-eth-20epoch"
      model_name: weight
   data:
      image: "/home/cyh/GazeDataset20200519/FaceBased/ETH-Gaze/Image/train"
      label: "/home/cyh/GazeDataset20200519/FaceBased/ETH-Gaze/Label/valid.label"

test:
   load:
      begin_step: 20
      end_step: 20
      steps: 5
      load_path: "/home/cyh/GazeBenchmark/exp/Implementation/Full-Face-eth-20epoch"
      model_name: weight
   data:
      image: "/home/cyh/GazeDataset20200519/FaceBased/ETH-Gaze/Image/test"
      label: "/home/cyh/GazeDataset20200519/FaceBased/ETH-Gaze/Label/test.label"

reader: reader_eth
